### ISSUE TITLE
Issue compiling markdown: --pdf-engine-opt=-emulate-aux-dir

### ISSUE THREAD

**Issue by nkrusch** [aubertc/au_ccs_dissertation_template#1]
- pandoc: 2.11.3.2
- latexmk: 4.70b
- Make: 3.81
- OS: macOS 11.6.5 
- pdfTeX 3.141592653-2.6-1.40.22 (TeX Live 2021)

1. Without modifying source, I run `make` in `md_version` and get result:

```
Latexmk: -emulate-aux-dir bad option

Latexmk: Bad options specified
Use
   latexmk -help
to get usage information
Error producing PDF.

make: *** [main.pdf] Error 43
```

2. I removed `-emulate-aux-dir` argument in the Makefile, rerun, and I get warning:

```
xelatex: unrecognized option `-aux-directory=aux'
```

The compilation runs for a while but fails with error (its not clear from output why).

3. I modified the Makefile so that both lines are removed:

```
--pdf-engine-opt=-emulate-aux-dir \
--pdf-engine-opt=-aux-directory=aux \
```

And now it works, and I get the same result as with tex (.tex version compiles without issues)

So my "issue" is about the purpose of these two arguments (in #3) and are they necessary? Otherwise I would suggest removing them.

**Comment by aubertc** [comment]
Thanks for the detailed feedback and test.

The only purpose of those options is to let pandoc knows that it _should not_ erase the `.log` file once it is done. It is primarily for testing / debugging purposes: if something goes wrong, then with those options you can check the file `aux/main.log` to try and debug it. Otherwise, you are completely blind, as latex's error message filtered by pandoc's  are sometimes a bit opaque (and the line number does not match).

[I had some discussion with latexmk's developper](https://tex.stackexchange.com/q/620968/34551) about those options, and no solution was completely satisfactory, if I remember correctly.

Can you run

```
cd /tmp/ && echo "Test" > test.md && pandoc test.md --pdf-engine=latexmk --pdf-engine-opt=-emulate-aux-dir --pdf-engine-opt=-aux-directory=aux -o test.pdf
```

and give me back the output? This will create a very minimal .md file and try to process it with those latexmk's options.

**Comment by nkrusch** [comment]
It is the same result

```
% cd /tmp/ && echo "Test" > test.md && pandoc test.md --pdf-engine=latexmk --pdf-engine-opt=-emulate-aux-dir --pdf-engine-opt=-aux-directory=aux -o test.pdf
Latexmk: -emulate-aux-dir bad option

Latexmk: Bad options specified
Use
   latexmk -help
to get usage information
Error producing PDF.
```

**Comment by aubertc** [comment]
Ok, this feature was actually only introduced with latexmk [V. 4.73](http://personal.psu.edu/~jcc8/software/latexmk/latexmk-473.zip), according to http://personal.psu.edu/~jcc8/software/latexmk/versions.html , so you need to update to latemk >=[4.74](http://personal.psu.edu/~jcc8/software/latexmk/latexmk-474.zip).
